pipeline {
	agent any
	
	stages{
		stage('Build') {
			steps{
				checkout([$class:'GitSCM', branches: [[name:'*/master']], extensions: [], userRemoteConfigs:[[credentialsId:'d8e3ca41-e256-4499-8185-bb50a759820c', url:'https://github.com/KamalDevHariharan/devops-hands-on.git']]])
			}
		}
	}
}